### PR TITLE
allow automated signing

### PR DESCRIPTION
**Pull request by retorquere**
This change allows for automated signing for unlisted add ons.

### CODE REVIEW

**Comment by retorquere** [comment]
This change makes Zutilo eligible for automated signing for unlisted add ons. The listed review process takes absurd long times.

**Comment by willsALMANJ** [comment]
Wow, if that's what it takes to get through the automatic signing process, I wonder how many bad add-ons it will ever stop. I guess the ability to revoke signatures is the more important component than the validation step. I'm not sure if they have some kind of whitelisting process in place, but I have been able to get Zutilo signed by uploading it as a Beta release with that `oncommand` line as is.

Has hosting on GitHub been working well for you? I hear people say that GitHub doesn't work well as a software distribution platform, but maybe they are talking about larger projects than a small xpi file. Can you tell how many users you have? Usage statistics and extension discovery are the features of AMO that are useful, though I'm not sure about the second one. I wouldn't be surprised if most of the users of Zutilo found it through a recommendation from @adam3smith in a Zotero Forums discussion that came up in a Google search.

**Comment by retorquere** [comment]
The validation process is a joke. They allow loading javascript from disk
from any place, and they allow downloading files... you could have an empty
shell which downloads all the nasty and it'd pass just fine. I guess indeed
the possibility to revoke is the major thing, but it's a major pain in the
ass the way they set out to achieve it. I never wanted to have anything to
do with AMO, given their continental-drift timed review times; passing
automated review by any means is the next best thing.

The releases from github are not fancy but they work, and I can release
whenever I damn well please. I upload each release automatically after my
Travis tests have passed, it's all fully automated, except the impending
step where I have to deal with AMO. They won't even take my offer to
volunteer to build a signing api.

I am not happy with the proposed signing as you might have noticed.

**Comment by willsALMANJ** [comment]
Closing this for now. Because Zutilo has already been reviewed on AMO, this validation error seems to be whitelisted (when I upload a new beta version, it gets automatically signed with the code as is). I will keep this in mind in case I run into problems in the future.

**Pull request closed without merging**
